sass:
  load_paths:
    - _sass
    - node_modules

# Handling Reading
exclude: ["Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"