sass:
  load_paths:
    - _sass
    - node_modules

# Handling Reading
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - circle.yml

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"